#!/bin/bash
# Quick Start - Test Execution Guide

echo "🧪 MAC Documents API - Test Suite Quick Start"
echo "=============================================="
echo ""

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "📦 Installing dependencies..."
    npm install
    echo ""
fi

echo "1️⃣  Eseguire TUTTI i test"
echo "   $ npm run test"
echo ""
echo "   Output atteso:"
echo "   ✓ 310+ test passed in ~5-10s"
echo "   ✓ No skipped or pending tests"
echo "   ✓ Coverage information (se richiesto)"
echo ""
echo "---"
echo ""

echo "2️⃣  Eseguire con COVERAGE REPORT"
echo "   $ npm run test:cov"
echo ""
echo "   Output atteso:"
echo "   ✓ coverage/ directory creato"
echo "   ✓ HTML report: coverage/lcov-report/index.html"
echo "   ✓ Target: >80% per statements, branches, functions, lines"
echo ""
echo "---"
echo ""

echo "3️⃣  WATCH MODE (durante sviluppo)"
echo "   $ npm run test:watch"
echo ""
echo "   Output atteso:"
echo "   ✓ Re-esegue test al salvataggio dei file"
echo "   ✓ Pressiona 'a' per eseguire tutti i test"
echo "   ✓ Pressiona 'f' per solo test falliti"
echo "   ✓ Pressiona 'q' per uscire"
echo ""
echo "---"
echo ""

echo "4️⃣  Test su FILE SPECIFICO"
echo "   $ npm run test documents.service.spec.ts"
echo ""
echo "   Opzioni:"
echo "   - documents.service.spec.ts         (40 test)"
echo "   - document-rendering.service.spec.ts (35 test)"
echo "   - markdown.utils.spec.ts             (50 test)"
echo "   - http.utils.spec.ts                 (60 test)"
echo "   - dto-validation.spec.ts             (30 test)"
echo "   - documents.repository.spec.ts       (50 test)"
echo "   - errors.spec.ts                     (45 test)"
echo ""
echo "---"
echo ""

echo "5️⃣  TEST CON PATTERN MATCHING"
echo "   $ npm run test -- --testNamePattern=\"Black-box\""
echo ""
echo "   Pattern suggeriti:"
echo "   - \"Black-box\"      → solo test black-box"
echo "   - \"Boundary\"      → solo boundary cases"
echo "   - \"Failure\"       → solo failure modes"
echo "   - \"create\"        → test che contengono 'create'"
echo "   - \"should.*throw\" → test che verificano eccezioni"
echo ""
echo "---"
echo ""

echo "6️⃣  VERBOSE OUTPUT"
echo "   $ npm run test -- --verbose"
echo ""
echo "   Output atteso:"
echo "   ✓ Stack trace completo per errori"
echo "   ✓ Console.log() output visibile"
echo "   ✓ Timing di ogni test"
echo ""
echo "---"
echo ""

echo "7️⃣  TEST PER DURATION"
echo "   $ npm run test -- --testTimeout=10000"
echo ""
echo "   Aumenta timeout se test lento (default 5000ms)"
echo ""
echo "---"
echo ""

echo "📊 Struttura file di test:"
echo ""
echo "test/"
echo "├── app.placeholder.spec.ts        (placeholder)"
echo "├── documents.service.spec.ts      ✅ 40 test"
echo "├── document-rendering.service.spec.ts ✅ 35 test"
echo "├── markdown.utils.spec.ts         ✅ 50 test"
echo "├── http.utils.spec.ts             ✅ 60 test"
echo "├── dto-validation.spec.ts         ✅ 30 test"
echo "├── documents.repository.spec.ts   ✅ 50 test"
echo "├── errors.spec.ts                 ✅ 45 test"
echo "└── README.md                       (documentazione)"
echo ""

echo "---"
echo ""

echo "🎯 Strategie di test incluse:"
echo ""
echo "1️⃣  BLACK-BOX TESTS"
echo "   Input validi, invalidi, tipi sbagliati"
echo "   Esempio: DocumentsService.create({ name: '', templateId: '...' })"
echo ""

echo "2️⃣  BOUNDARY / EDGE CASES"
echo "   Min/max values, zero, array vuoti, stringhe lunghe"
echo "   Esempio: parsePagination({ limit: '999999', offset: '0' })"
echo ""

echo "3️⃣  FAILURE MODES"
echo "   Database errors, network failures, input corrotti"
echo "   Esempio: documentsRepository.findAll() throws 'Connection lost'"
echo ""

echo "4️⃣  INTEGRATION TESTS"
echo "   CRUD workflow completo, flussi end-to-end"
echo "   Esempio: create → read → update → delete"
echo ""

echo "---"
echo ""

echo "🔍 Esempi di bug che questi test CATTURANO:"
echo ""
echo "✅ Name documento vuoto non rifiutato"
echo "✅ fieldValues accetta null (dovrebbe rifiutare)"
echo "✅ Offset > total non gestito (SQL error)"
echo "✅ UUID malformato non validato"
echo "✅ UTF-8 byte counting scorretto"
echo "✅ Placeholder con spazi non rejettati"
echo "✅ Zero e false considerati come 'missing'"
echo "✅ Transazioni non rollback su errore"
echo ""

echo "---"
echo ""

echo "💡 TIPS:"
echo ""
echo "• Usa --watch durante sviluppo per feedback istantaneo"
echo "• Esegui --coverage prima di commit per verificare copertura"
echo "• Leggi test/README.md per documentazione completa"
echo "• Aggiungi test per nuove feature (segui template)"
echo "• Non skippare test (.skip) - elimina prima di commit"
echo ""

echo "---"
echo ""
echo "✨ Ready to test! Esegui: npm run test"
echo ""
